# 描述：
desc '使用 Manager 这个航道, 可以快速的对自己的私有库, 进行升级维护'

# 使用方法 ： fastlane Manager 

# 本航道名：Manager
lane :Manager do |options|

# options:传进来的参数，后面的tag和target是对应的字段
# tagName = options[:tag]
# targetName = options[:target]
# isSource = options[:IS_SOURCE]
msg = options[:msg]


# 具体这个巷道上面执行哪些行为

# 1. pod install
# cocoapods(
# clean: true,
# podfile: "./Example/Podfile"
# )

# 2. git add .
git_add(path: ".")
#    git commit -m 'xxx'
git_commit(path: ".", message: msg)
#    git push origin master
push_to_git_remote


# # 验证tag是否存在,如果存在, 应该删除本地标签和远程标签
# #if 判断标签是否存在
# #    执行删除本地/远程标签
# #end
# if git_tag_exists(tag: tagName)
#     UI.message("发现tag:#{tagName} 已经存在, 即将执行, 删除动作 🚀")
#     remove_tag(tag: tagName)
# else	
# 	UI.message("tag:#{tagName} 不存在, 开始提交 🚀")
# end


# # 3. git tag 标签名称
# add_git_tag(
# tag: tagName
# )
# #    git push --tags
# push_git_tags


# 4. pod spec lint (注意要添加公、私仓库)
# pod_lib_lint(IS_SOURCE:1,allow_warnings: true, sources: ["https://gitee.com/LFCoding/FreemanStaffSpecs","https://github.com/CocoaPods/Specs"])
#    pod repo push XXXX xxx.podspec (注意要添加公、私仓库)
# pod_push_Custome(IS_SOURCE:isSource,path: "#{targetName}.podspec", repo: "FreemanStaffSpec", allow_warnings: true, sources: ["https://gitee.com/LFCoding/FreemanStaffSpecs","https://github.com/CocoaPods/Specs"])


end
